version: '3.9'

services:

  # 1. User Interface
  yelb-ui:
    image: mreferre/yelb-ui:0.7
    ports:
      - "${YELB_UI_PORT}:80"
    depends_on:
      - yelb-appserver
    networks:
      - yelb-network

  # 2. Application Server (Backend)
  yelb-appserver:
    image: mreferre/yelb-appserver:0.5
    environment:
      - YELB_DB_SERVER=${POSTGRES_HOST}
      - YELB_REDIS_SERVER=${REDIS_HOST}
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - yelb-network

  # 3. Redis (Main Cache Server)
  redis-server:
    image: redis:6.0
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
    networks:
      - yelb-network

  # 4. Redis Sentinel (Optional monitoring layer)
  redis-sentinel-1:
    image: bitnami/redis-sentinel:6.0
    environment:
      - REDIS_MASTER_HOST=${REDIS_HOST}
    networks:
      - yelb-network

  redis-sentinel-2:
    image: bitnami/redis-sentinel:6.0
    environment:
      - REDIS_MASTER_HOST=${REDIS_HOST}
    networks:
      - yelb-network

  redis-sentinel-3:
    image: bitnami/redis-sentinel:6.0
    environment:
      - REDIS_MASTER_HOST=${REDIS_HOST}
    networks:
      - yelb-network

  # 5. PostgreSQL (Master DB)
  yelb-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      postgres -c wal_level=replica
               -c max_wal_senders=10
               -c wal_keep_size=64
               -c hot_standby=on
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - yelb-network

  # 6. PostgreSQL Replica (streaming replication)
  db-replica-1:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - yelb-db
    command: >
      bash -c "rm -rf /var/lib/postgresql/data/*
               && PGPASSWORD=${POSTGRES_PASSWORD} pg_basebackup -h yelb-db -D /var/lib/postgresql/data -U ${POSTGRES_USER} -Fp -Xs -P -R
               && exec postgres"
    volumes:
      - replica1:/var/lib/postgresql/data
    networks:
      - yelb-network

volumes:
  pgdata:
  redisdata:
  replica1:

networks:
  yelb-network:
