services:

  # 1. Frontend (UI)
  yelb-ui:
    image: mreferre/yelb-ui:0.7
    ports:
      - "${YELB_UI_PORT}:80"
    depends_on:
      - yelb-appserver
    networks:
      - yelb-network

  # 2. Backend (Application Server)
  yelb-appserver:
    image: mreferre/yelb-appserver:0.5
    environment:
      - YELB_DB_SERVER=${YELB_DB_SERVER}
      - YELB_DB_USER=${YELB_DB_USER}
      - YELB_DB_PASSWORD=${YELB_DB_PASSWORD}
      - YELB_DB_NAME=${YELB_DB_NAME}
      - YELB_REDIS_SERVER=${REDIS_HOST}
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - yelb-network

  # 3. Redis (Cache)
  redis-server:
    image: redis:6.0
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
    networks:
      - yelb-network

  # 4. PostgreSQL (Database)
  yelb-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - yelb-network

volumes:
  pgdata:
  redisdata:

networks:
  yelb-network:
